### ISSUE TITLE
Return type from the deal() function

### ISSUE THREAD

**Issue by rciampa** [sespinoza/cucumber_lab3#1]
We need to determine how you want the data _file path and hand total_ returned. At the moment I have stopped adding to the **deal()** function until we figure it out.

_My thinking: is_ that you could call the **deal()** function from the index.php and work with a data structure for display. If anyone has a better idea then please add it.

**Comment by brandoncsumb** [comment]
I would just call it from index and then have it return the card value to the table spot in a for loop. basically what we did with the led board but instead replace it with cards

**Comment by rciampa** [comment]
Do you want to work with Andy to finish that part of it?

**Comment by andyrichardson** [comment]
Hey guys, I'll make a function which returns the current card value once I return home (within the next few hours).
Andy
On 18 Sep 2015 12:47, Richard Ciampa notifications@github.com wrote:Do you want to work with Andy to finish that part of it?

**Comment by rciampa** [comment]
Resolved with $players array.
